### PR TITLE
Feature/signup welcome page

### PR DESCRIPTION
**Pull request by ldanielswakman**
@gcg Can you shine your light on how to add this new welcome page (`/hosgeldin`) to the signup flow? We need to be able to handle
- both normal and FB signups to land here
- be able to get the `redirPath` variable and pass it as a path to the in-page redirect & button

### CODE REVIEW

**Comment by gcg** [comment]
there is no route for /hosgeldin right now but if you create one, just replace the 

return redirect()->intended... 

lines at the end of postRegister and getFacebookLoginReturn in AuthController 

with 

return redirect('/hosgeldin')...

**Comment by ldanielswakman** [comment]
@gcg Thanks, done that. How about getting the `$this->redirPath` as a variable in the view?

**Comment by ldanielswakman** [comment]
@gcg I am going to merg this since it works now, but it would be great if you can get back to me on that last question about `$this->redirPath`

**Comment by gcg** [comment]
as far as i can see we store that one in the session. 

so you can use it in the views just as we used it on the construct function at authcontroller. 

```php
$redirPath = (!empty(session('last_page')) ? '/'.session('last_page') : '/');
```

**Pull request merged**
