### PR TITLE
Feature/homepage updates

### PR DESCRIPTION
**Pull request by aniluyg**

### CODE REVIEW

**Comment by ldanielswakman** [comment]
@aniluyg it's looking good; just one question: is it possible to implement a 'X dakika/saat/gun/hafta/ay/yil önce' functionality?

image

I'm sure there is a standard library for this; see here:
https://laracasts.com/discuss/channels/general-discussion/minutes-hours-day-ago
https://github.com/briannesbitt/Carbon (I think we are already using Carbon...)

**Comment by ldanielswakman** [comment]
Regarding 'X gün önce', do you have any idea how to implement this smoothly in Laravel @gcg ?

**Comment by gcg** [comment]
You want to do this on the client side (JavaScript) because u want your
relative time to be relative to the visitors time.

I use and recommend moment.js for this.

**Comment by aniluyg** [comment]
@ldanielswakman  i've just integrated moment.js and tested it. I will infrom you when i implement relative time for updated ideas.

**Comment by ldanielswakman** [comment]
@aniluyg okay great! Let me know if you need anything from me for that

**Comment by aniluyg** [comment]
@ldanielswakman ok, you can check it in staging env.

**Comment by ldanielswakman** [comment]
Looks great @aniluyg, so cool that this works. Last thing before we deploy: it's now in English, even when the app language is in TR. Can we make the time appear relative to the app language?

**Comment by gcg** [comment]
what i did back when i was using moment in a smilar setup was: 

I set a hidden div in html with the laravels app::locale input as a data attribute like so: 
```html
    <div id="AppLocale" style="display:none" data-locale="{{App::getLocale()}}"></div>
```
and than i initiate moment after i read this inputs value like so: 

```javascript
$(document).ready(function(){
    var loc = "tr";
    if ($("#AppLocale").length > 0) {
        loc = $("AppLocale").data('locale');
    }
    moment.locale(loc);
    initMomentsJs();
});

function initMomentsJs(){
    $('.moment').each(function(){
        var d = $(this).data('date');
        if (moment(d).isValid()) {
            $(this).html(moment(d).fromNow());
            $(this).removeClass('moment');
        }
    });
}

```

**Comment by gcg** [comment]
this was a really old project so laravel locale thing might be something new.

**Comment by aniluyg** [comment]
I had set locale for moment.js with this code : moment.locale('{{App::getLocale()}}');
When you change language you can see lang of time changes. I tested it in chrome and safari.  I think there is an issue when default lang is EN and when the page load first time. I will have a look at this when i have time.

**Comment by aniluyg** [comment]
@ldanielswakman can you check it again?

**Comment by ldanielswakman** [comment]
@aniluyg awesome! The moment.js implementation seems to work great, both for TR and EN. Merging this

**Pull request merged**
