### PR TITLE
Allow comments to be edited and removed by superadmins

### PR DESCRIPTION
**Pull request by ldanielswakman**
### Backend:
- [x] Make `editComment` and `deleteComment` controller actions available for superadmin users

### UI work:
- [x] make comment edit button available to superadmins & admins (if own comment)
- [x] update edit/delete comment routes for superadmins from /muhtar/XX to /admin/XX

### CODE REVIEW

**Comment by gcg** [comment]
@ldanielswakman I added comment edit and delete related 3 routes to admin controller as well and they should be available to the admin users under the routes; 

`GET admin/edit-comment/{comment_id}` to load the view edit comment 
`POST admin/edit-comment/{comment_id}` to save the comment 
`GET admin/delete-comment/{comment_id}` to delete any comment.

**Review by gcg — APPROVED** [review]

**Comment by ldanielswakman** [comment]
@gcg okay I fixed the UI here; tested it locally and it seems to work; can you review and merge if all good?

**Comment by gcg** [comment]
all looks good. lets wait ci to do is work and we can merge it

**Comment by gcg** [comment]
actually you merge it in your own time so you can test it on the production for one last time.

**Comment by ldanielswakman** [comment]
Ok, will do! Just to confirm: if I merge this into master, it will be automatically deployed to the single live environment we have now, correct?

**Comment by gcg** [comment]
Yup. That is correct

>

**Pull request merged**
