### PR TITLE
add tags data binding to report page

### PR DESCRIPTION
**Pull request by aniluyg**

### CODE REVIEW

**Review by ldanielswakman — CHANGES_REQUESTED** [review]
Looking good! Can we add the click behaviour to tags as well? When you click on a tag, it should filter the list (and later on the map) of ideas and only show ideas with that tag. Make sense to do in this PR; or do you want to create a separate thing for that?

**Comment by ldanielswakman** [comment]
@aniluyg since the last commit, staging doesn't seem to work anymore? http://stage.muhit.co/report/district/12

**Comment by aniluyg** [comment]
@ldanielswakman , it's weird. There is no problem in codeship build process and i can run application in my locale without problem. Can we see server logs or system health for staging environment?

**Comment by gcg** [comment]
whatever code is running at stage.muhit.co/report/district/12 (did not look at the code at the moment) requires lots of mem that our staging env does not have so it fails with 

[Wed Dec 06 17:14:25.088304 2017] [mpm_prefork:error] [pid 7879] (12)Cannot allocate memory: AH00159: fork: Unable to fork new process

since the main php fork is dying the app can't send the php errors to sentry as usual. 

Whatever is working there needs to be trimmed down. Hola at me if you guys need help.

**Comment by aniluyg** [comment]
i've just checked out new branch from master named 'dev' and pushed it to origin. Codeship build was succeed but staging environment is still unreachable unfortunately. I was expecting the staging environment runs successfully with master branch as production environment. What do you think about this?

**Comment by gcg** [comment]
@aniluyg just to FYI if you want codeship to deploy the code to stage.muhit.co you have to start your branch name with the **feature/** or **hotfix/** prefix. Otherwise it will just build and not deploy. 

Sorry if this is not documented anywhere.

**Comment by aniluyg** [comment]
I pushed the 'feature/reset_to_master' branch to origin but i'm afraid it didn't work : (

btw i saw dev brach settings in deployment tab in codeship i think it's settings are same as 'branch starts with feature' but i'm not sure. I am new to codeship.

**Comment by gcg** [comment]
Just checked from codeship as well yep you are right, dev also deploys to the stage. 

Also deploys are fine and they are going w/out any problems. 

```
2017-12-07 13:37:05 UTC-0500 | INFO | Environment update completed successfully.
-- | -- | --
2017-12-07 13:37:05 UTC-0500 | INFO | New application version was deployed to running EC2 instances.
2017-12-07 13:36:34 UTC-0500 | INFO | Deploying new version to instance(s).
2017-12-07 13:36:27 UTC-0500 | INFO | Environment update is starting.
2017-12-07 13:17:52 UTC-0500 | INFO | Environment update completed successfully.
2017-12-07 13:17:52 UTC-0500 | INFO | New application version was deployed to running EC2 instances.
2017-12-07 13:17:35 UTC-0500 | INFO | Deploying new version to instance(s).
2017-12-07 13:17:28 UTC-0500 | INFO | Environment update is starting.
2017-12-07 13:09:57 UTC-0500 | INFO | Environment update completed successfully.
2017-12-07 13:09:57 UTC-0500 | INFO | New application version was deployed to running EC2 instances.
2017-12-07 13:09:23 UTC-0500 | INFO | Deploying new version to instance(s).
2017-12-07 13:09:16 UTC-0500 | INFO | Environment update is starting.
```

Don't know why stage.muhit.co is not loading, will look further and let you guys know.

**Comment by ldanielswakman** [comment]
@gcg @aniluyg thanks for checking; it's a mystery.... let me know if I can help w anything

**Comment by ldanielswakman** [comment]
@aniluyg that seems to have done the job; thanks for that. Stage is now working again. Regarding the functionality, it's not working exactly correct. When you click on a *kategori* (either in the pie chart or in the list), the idea list (and later map) should get filtered to only show the ideas with the currently clicked *kategori*. Is that manageable?

Also I saw another bug: in an ilçe with only 'new' ideas, and no other types, the chart shows up purple instead of blue. [See here](http://stage.muhit.co/report/district/1). Can it be because of the order of the types? Should be 1) new, 2) in-progress, 3) solved. It works fine when there are [multiple types](http://stage.muhit.co/report/district/12) though.

**Comment by aniluyg** [comment]
@ldanielswakman  i think i misunderstood the task to do after category chart clicked :) For now when you click kategori pie chart kategori list is being filtered as we did in idea chart and list :D 

OK then you want to filter idea list when we click category. You know we also filter ideas by status. So, if i dont get that wrong there will be two filter. İf i select 'bisiklet' kategori and 'gelişmekte' status the idea list will only list ideas which are in bisiklet category and gelişmekte status. And kategori list will still remain same; it has nothing to do with click event on kategori chart?  Is this ok? 

Also i will look at color issue of idea chart.

**Comment by ldanielswakman** [comment]
Right good point, indeed both pie charts will filter the idea list (and later map), not the kategori list. Well it might be simpler if we just have one filter at a time, right? That would be fime

**Review by ldanielswakman — APPROVED** [review]

**Pull request merged**
