### PR TITLE
Develop/redirect after login

### PR DESCRIPTION
**Pull request by gcg**
can you please test when you have time from different pages and merge if everything looks ok. 

thanks ^.^

### CODE REVIEW

**Comment by ldanielswakman** [comment]
Reviewed it on stage.muhit.co; mostly works fine! 1 small issues found:
- [ ] same should happen for logout: when user logs out, if they were for instance at `/issues/view/66`, they should still be able to see that issue publicly.

**Comment by ldanielswakman** [comment]
Btw I couldn't test if this works as well for Facebook login; because it doesn't accept FB login on stage.muhit.co domain.

**Comment by gcg** [comment]
yep, it was because a config error, I set up the correct domain for redirects in facebook. 

but it doesnt work I guess.

**Comment by gcg** [comment]
it isnt working because its not on the stage :) you deployed something after me I guess. Merging this one.

**Comment by gcg** [comment]
looks fine, 

Always like the idea of removing code :)

**Pull request merged**
